using System;
using System.Linq;

namespace PrepareForEGE_MishaPolykovsky
{
    internal class Solutions_24
    {
        internal static void Start(object use = null, ISolution.StartupOptions startupOptions = ISolution.StartupOptions.Include)
        {
            ISolution.Start(new Solutions_24(), use, startupOptions);
        }

        internal static void Solution_36()
        {
            string s = "ABEABAFDBDCDBBEDCCDDFDDFFFDDEEDEADFCDCDEEDBDBADFEBABEBDEEADFBAFFCEBEBCDCFCFBAAFADAADFDCCEEAFCFAEDBBCDFBDFECCCEDEFFCEDEAECFEDFFAAEAACEBEDEFEADCEBEDACFFBDFFEFBBBBFDCBFCAEFDEEAEADEECBDFAFCBBBEFFBBFFFAABAECEEEFCFECABAFDFDFFABFFFDBEEEFAADDFCFEEAEEBFCEADCFDACCEFEEFAFAEDEEDBCCCDCDFEFFBABCAABBBDDBBAAFCECBDCAABAEAEAEFFAEFAFBBFEDAFDBDDEAFABBEFFEADADFCBABDDEAFDDBACCEEBDBDDEDABADABACABCEFDCFCDEDEFDBAEDABEEACFCADCDECAAEAAADAEEEFBCEDECFEBAAEAAFBADFEDBFABBEACBACCCCDCDBDBDDDADEEBBCFFEFACCCCAEDBDABABBAEACCCCBDCEAEBEFECCECEBBBFEDDFADEAEECDFCBDDFCAECCFDBBCCCCDFBDADDDFAFBFCFDBCCFDDEDABBDEBBBFBACFBABEFDFFEADFDFBCFDCADFBCEBEFEFFAEDEFBEABBFDCBAEBDBAEFDFBDFCEECBEBEBDCEBDCBCFEFECFDBBBBDBCBAADFFECFDDBCBBEABAFCDDBAEAEDEAEBDACFEDDEAADBEECEDACABEDBDEBBADADFDCDDEBEDEACBAABDCCAFDEFBFDFACFFBFFBFFEFBDEEBECCBEDDEFDBDEADEBFCBFBCABEEABCCDBBFEDFDCEBABCBFDCCEBBBCBCABFEDCAECEDFBBEDBCCBDAEABCCDEAEFBBAECFAFCBEBDFEAEEFEEBADFEEBFADDEDAEFEABBCBABCFBBAEFBDDEECDDABDEDDAFFCFEAECBFFFFBDBFFCFDAFBBAAAFCBFFEBBEABCEBAEAABCEFAEEBFBFCDECFDDAFECECFEEFFCEDACCCABCEFFCFFCEAFCFDEDABAECCCABCCEEEAABAFEBFBBBDFDDCCBBACDEFACBFAFAADBFEDDFDDBDBADEDBDDBADDCCFCAAADEAFAEDAADBDDADDAEBBEEABBBEACAEFABBCCDFDBCABFDFEFBAFBAECFABFBAFEBEDCDFCCCFBABCBDBBFECBEDAAFDFACAABEDCBFFABFFABBAEDADAACABABCCFDEFCCCCFABDABEBABCFFBDBFCECCFAEBFCCABCDEAADCDFEBEDAABACDCFDCEACBFDEFDDFFEBBDCAFFAFCDDDFAACFAFDCDFCFEFEBEBBCDBBACECDBAEFDFDEEDDADABDFDFBEFDACFBCDBEAADFCADDCDFFADDFBBCCCABFDBCEBCEFADADDCEEEFAACCBBEAEAFFEBDDAEBAFFEDCBBEDBCBFFCEAACFCFEBCADBEDBEFAAFCAADCEBDDECBFDFADFEBCDAFCAAEAFCDDFEBFBCFBBEFDEDBAEABFDDCBBFDDAFEFADECCFBDBEDBFCBCCEEDFAFEDDEEDFAEABDBABDEEFACFEADDABCCDADDEFAADAADEEEAEFDBCBAACDDDBDAAEACEDDACDECFFEABDFBDDFEECFCCFDCACBECEBFDFECDBFFCEFBBECABBABBAEBACADFFBBEECEFEDAADEFFFAADBFEFFFBCAEEBADECCFBAAFDFCAAFEFEEADDAAFFFDEBBABDFBFEAFEEAEEFEDCBFDCDEEECCFBCBABFFCBDDEEADADDADFABEFBDDCDACDCFDBAFECECFDBEAFCBACFFAFBDECAAFCAACCBBFBABFCDECFEDAEAEBDFACAFDBDDCFFABECDEBCCFFBDCBDFCFAFEBEDACDFCEAEBBBBCDFCAACCCFFACFDBABCCFDFBEEFDABEEEEFFCFEACBFAEDBBBDABCAABAFCABFACFCEFAAEFDEFBBFAEDBBFCFADEEBFCFCDFCAEFBAEFADFADAEEEACFFFBFABDFFAACAEBBFFDFABBAFFFACCCABFBFCACFAFFFCBAEBCCCBEBFCCDDDFFCDDEAAABAEEBEABCDBCCBCBBBCEEFDDECFDEEDEDEFBBDAECCDCEECCDBEFCBFCDAEEBDAEBFCFCCABFAEAEEADACDDADDFCEFEDCBDCCDADDFCCDDDFFEAFCABBBDFDCDCDAEDAFAEDDFBBEDBCDADCECBADFDCFACBADBFEBCCDEDBCBBDFBCDAADFCFBFBCBEBBCCDCCFCFFEFFDAAADADBFBEEADBDEABABCCDCEBCBDBEAEAEBBEFFCFFEBABCBAAFAAECBEEAEBBECCDBBDFAFCAAFFCEFDFFCADEEEEFECBFFCEDDBCDFEFBFDFBFFBFCFEDEEAAABBCDCAECDDAABDFCCAEECAFFFACEABCBACEAECCEDEAFDAFBAAEFDACDAFCCDAFFEFEDABBADCCFBACFAFBFABCDFAEEEAEABFAEBDEBEBBCEEEBABCAEDADDDCCCEBDDECECEAACBCCDCBCCDEFFFFCDEDEACECCBFDBEAFFCCFDAACECFAEFEEEDAFEBAACABFABDBFECDBCEAEAAFDACDABBFFECEBEEDEABBDDADBACBFBACAFABBFCEAFAFCAEDEDCDDBAEBCFCCEFBFADCBCEBDCDFABEBFCBCDDBEACAAEADCFEAEFCFEBFCADBBDCBFDDACAAFEFEAAFDCBDDEAECABEACABEBFEAADFCCECCADEBFACBFBBDDACFFDBBBEEEAACCAFFDFCFDAEAEEEAAAEBCBCACBEADCFBACBBAEADFBAAABEBFCFAEEFDEABABEEEFEAFCECDADAABBEFDCADBCCDADAABECFEFBDCDFDACCFBCFADABAFBDDFDAEAFDFEFBDFACCFDBAEDBBBECDEFFBFBDCDBCCFFAFFDEEAABBEFBDCCFEFECFFEEAEAFBFEFDCCDDFBAFDABBFCFFBBABDBCFAAAEFFEACBBCBCECCEBBDBFBCCDACABBFAAFABEBBBAFFDEEAEBFAABFFBEDFAFBBEBCCFDCFDBEFAFABACDEBCADDFFDECDEBDBCDCCDAAECBCEFDAEBABABFFAFADDDEABDBCCFFADAAEEBCDDEBAFBABDECABDDAACBDBCEDDDADDCACCDCFBDFAAEECFDEDEFDBCCEFEFECDCBFCAFDADADBEAAFFDCCEDEBCBBCAAEEDDAFBCFBEAECDFBDBBDEFBEACDDBACABDBEBEABCDFEFADCFAFBEDBFBEEBDCCADCBBEBDECFAADABFDDFDDDEFBDBCDABCFBBDAFACBAACDEABAEADBBBFBFCBCBFFCBADFEFACFBECFDACEBFDBABAAFFDEBFAEEACECDCFFAFFADECCEBDDFDFFEECFCFDAFCBCCEECBDEAFDEEFBECDBFFFFABCACDFFABEBEBEFFABDCFFCEDACCDEEDAFCEABCAEDDEBAACCDDBBDDFBEFFAFDECDFBAECCACFCBAEDBCACDBBEAADFDBDFEEEDAEAEFFDECFDFCACAFEDFFEDECDDDBEFEDBCECDFAFDAADAAFECACEDCBBECCAECDDBDAEDDEDCEDBFDAFEBFEBECCCEDBBBDFFBEFBDFEBDFBCAEDABCBBCDBCCADBEFFFECEDDEEDBDECFCBCBBBDBBCBBEFBEDBACABCAABAECFBBACCFAACEDEDDAABDEFDCDDCDDCBCDDFFDEAFCFEDEDBDEADDBBFFDAEFFEDDFDDDEAFDEFDAEDDAEFFFFBFEFCDFDDBABBBCAADBDABCACFFAEAEBADCCAAAFEBDBCCFFAAFBDCCFAFCFDCFDBCACEFEBBEADEAEFFBFFEBECBDAACABEBCDCACBCECFEBDBCFDACAAFEBAFBEBBCFADFAEDCEAACBBEEDCEEEEDFABFDBBBDFDCFADBCABFEEADDCDBEDCACFBCDADEFDCDEFDECFBBFDCFFADCCCDFCBBFEBDAEFFEAFDFFFEBBCBBDBAAFFAEDEDFCAFFCDCECCDCABEFBDDDAABDBBBDBCEBADCCBACBFCDACEBBDCCFDCCFBBBCDDACECACDBDFFADCBCAADEBDAFCECBFBAFBCBFCBFABAACEEDDDCEABDBEACEEEAAEFBEBFFFCCEEABABDBFCBFACACAEEFEDCDFECAABFCDDFBDBEDECDDDCAFFCEDCFCDECDEFEEACEECDABCEEDCACBAFCBDBDECBEFCBDCEDFEFFCDAAEAEFBECDDFBAEEFDCCEDCACCEEBFDECFCEEFCFEDBEFEEBEADDEDAAFADDFADDAEEEDEEFACCCCAABECBAFFEEBAFAFBAFADFEBDAAABAFFDCFCCDDEBAADECABFFAFFFFDECFBBFEEEDDBEBCDCBCDBDAEACAFDDECDDFAAFFCEEDFCABECABDBBFDFADEFFEFFFFDFCADCEACAAECAADEDACFBFEFBDFAFDEBBCCFEBCCDECAAEEAABAAAFCBEFAEDBDBCDCDCBFDBFAFDCBCBAEAEBCAEAFDCAAAECABEDEAFDACAEBEDBACFDADBFFDCBDEADFCEECACDFFEADBEEEBFFABFCAEBABEDBFECBBCEFFEEFCCFCCCFEFEDEFFBEECDBFBCCCDEFAFEDEADDBAEFCDFCADAAFFFEDABCBBBCCDEAFFCDABDFCEAADDCCCCFDFEDDAEDFEDDEABEACDBFAFFCEEFBFEFDABFDFDEBAFDACACCBACEFFCFCDCAAFDABBACDFBBDADAECACDCEEFEECDEBCCCCAEFFBECABFEFFDECEACBDCEDFEEDABCBEBACEBCFBFFBBCFDABBCBDFABFEBFBBCFBCBDECFDFFCDFABDBBDBBCCBDABBADCDEBDAFEDDABECBEEBBBBEEEEAEAFABFFDFABCECDDEAACCECFCBBCCEDDBFDFAAAEEDADFAADBFEBFFEBCDDEABACBFDCBADBFCEFADDCAEBCABCBFBDEDBAEBCBEECADDCEDBFECACBADACEFABFFABEDDDEFDDAEDFFFAEDEFABCBCEDBEDDCEFBFEFFAFDFCDEABCCBCFCECFAFBAEDBAFCDEFCABFADDDAFECBABEEFFEFAFBABDEDBEAADECAEEADCDFBCBDDCBAFCDAEBBBFDDBADFDCCCDBABDCBDECBABADEEDEBEEEAFFFFABBADBEDEFBCDFFEFFFEBDBAEECBCBFDAACBFECDBCFEFFEECAAAFBDBDFCACCDCBBBCFDFFFAEBEAFBCFEFBECAFADABCCCADCEDCBDABDBEFBACFABCAEEDEEBBEFDEAAADDAFDCACCAEDAADAECDAECAAEDFDFBCECEFADFFCFFAFEBAFFEFCDBCDAEDDABCDDFDACAEAECBEAEFEEFACBBBFBEADECDFDFEADDDECDBAECBEDEEDDEADEAEEDFCCEDEFACAFDCBEFDCDFBDFFECABEACDCFFBEBFFBEACDFDFFEADDBDDCCEFEAAFCEBACFFBBBCADBCDFCEAEDACBCCEEDEFBADAEDCDABEFCBEADCFBDEDFDDDFDCBEECFEECCCCDFBBFADEBBDCABFFCBAAFFCFBCDADADBEDEFECBCDAFFFBEAEFEDDCDDDDECAECCCFFBBECCFEDDEBAEDBFBEEFCAAABFFDCBABBABBFFCDCBFFBCDFFDFACDEDCABFFFFCEABADECEDBDDCACFFCBCAEECACCCBDABFFEBFDCEAFBFACBDDBDDAABEBBBCDCBADAECECAFBBCDBFCEEACABEEBCFCBDADCECFCAEDADBFDDCCFDFEBAAAFCEEAADCDDCAFCEBCCAFABEAAFBACBADBEBDFEDDDFAEEDAAAEBACDDEFBCEADADCDFFFBFEEACBFBFABFCBDADFDBDCCBACFDABDDEBDAFDBDBBAEDDEFDBFFAFDFFBFDFFFBADECBBBCCDECFCBAFDDDFDABADDDABBDABAFFCECAFCDBEADDBDEFBFFDECACFFBEABCBFBDDCEFCFFACDCABFAAFFFECBCCABDEADEEEDCAFDCEEECCDBFBEBEDEABCEFAAEDDEDCCFDEEBBFFAACEABCEACBCACFBAAEFACECBFDDCDAAFCEEFCDEFFDBBFFBFABCADAEBCCDFEEFBEAACCFEFFEFDBFBDABBBCEDBADFDDFBCCECCBECAEACFFCDFECDBAADECBFDEBDACABBBAFABCDCEFDEFFEFBADCBCCDFECCDDCDBCBCBFAFCBFCAACAECDDFBCABCADEDCDDEAFEEFBCEEBBFDCDFDFCDBEACACCFFBAABBEBEBDABBFEACADBDCFCCDACAFDCDCBBDFDEABCFBBFFFEFFCFFBAFAAEBEEDAFFBFDAABFCAEBEEACEFFABCEDCCBABECEFDFADEDCCCACBADFCFFBDBEBCBBDFDAECCFBEAAEFFCDBFEFDBDCADABBCEDEAEBBBFEBDBACCFAECECEEFAAEEDEDDAAEFBDADBACABACCBEACAFCECECBDFFDDAEAFCBBEFCCCBCEBDBEEAFEDCBBBDDFEAEACDFEBABDAFAADEFEAFFACFDEAACECCFAEFFDBEFBECDCDFCFEBEBBACBACBDCCCAADBBFBCCAEDCCEDBAABDFBCEECCBAAACCEFCEEAACBDFDDFBEDAFCCADCDFEFFEABBDFDAEDDDAEAFDCBDCADBCBACECCAEDDDFBBFCCACDDAEECABADFFBEAAFFABDDFBBBEFACAEEABEEAAFADEFDEAECBDACECCDECBBFBFABCBBDCFFADEAECDBAAFBAEEEBFCBDBDAECDFDDADAEDCCFFEADAFCEEEABADFDFAAFEFEFBECECFFAECCBDDEDDFCADFCCBCFBDCDEDAEEEBBDACEAAEBEFFCADEBDBFDDFEDADFEBFFFFCFFECAFBCDEBEEEDACDBEABAEFFEBBEDDAAFDEEBCDDACFBBAACABDCBDBEEBFFFFBFDCFBFEBFAEFFCBDCDCACFFDEBECDDDACBCBAABFFFCBADAFEABDBFEAFACFEABEFEDDBAFCFAFDEACCCCEECBBFACBDDABCDEDCFFAADFDEAABDCABFCDBDAAFBBDDDBEBDECEEEECCABBFAEFFADFADEAEADEDAFACFEECFEDDBDFCABAEFEEEABEFADDFDAADEEACDDCFEABBBBDEFADFAAEFFEDCDEEEDDCDBEBBFBEFBBFCAFDEDEFACAEFDFADCEAECCFDEEEBACEEADBCFBDACBDAADABECDECEBDBDDEAFABCDCABDEFCFCEFCEBEEABDCACEDFBCFCCAAEFFEEDDCEFAEABECBFAAECCDEAABDEDFFAFCCDBDAFFEFEFEABCCDAAEDBFACDEFCFECABAFDEBCFEDACDEBECFAACDDEBCDBEDDFAFECBADBBFEBDCBBCFBFCFEEAEBCACEDEDFFCCAFAFDCAACADADABCEADDECBFFCCBDCDADEAAECCFDDCCACDDBEABCEEEBABACEBAEEECFEDCDDDFBECEEAFDABBECFDBBDCBDBEFABECABBCCADBFFCDEFDBECBCEBDADCCCBBACAAEAEBEDCAADFCAEDEDBECEFEFBBEFFAAFCBADAEAECEFFECBEFFEAABEAEAADDEABDFACCEDAFCCBEFEBCCFEADABDDABAADBDADBFACECBFDEBCABCEEAABBDCBEEBBDADCDEFADFADBEAECBDFCDCBFDCDFCCBCFECEDAFAEBFABADCDECEDEDEDECCAAFCEDEDEBCFFCCCBBAAAEBAEDBEDDAECADBCBFAFBEBEBACDADECFEADCBCAEADDEEAAABBFAFDDFBCFBCDFCABEDAEADFDEDAFDDCEFDABABAADEBCEFFCAECDFEDABFEFCBFDFDDDCCCBECFDFBDBFFAAABFDBABEADBDABEEDECAEABADEABFEFCAFACEEBACFBCEECDBFBEEDBCEDEBAADEBBAFBFDADDFBEDCAEFFAADABAFBCDAEEADBCCFFBCADBDCFACAEBAFCEADDCBFBABEDBCAAAFDABACAFEBCAFFDDBCABAEDBDFCDDDBBCBBEEFEABDFAEEABCFCCDCDEFEADADFFEBFDBFDFCFBDBCAAFABDDECFDABAFECBBABADBDECDEBFEBEFEEAEEFFEABBCCADFAFBCACAFAABDADFEAFEAEFBBCFCBFEBEDECEBDCCECECEDAFAFAACDDCCADDFDFECEEBCBEACECFEADDCDEDBEBADDCFEBABBDCABACBDEFCFCDBDCCAACECDEDBBCBAADAFCEEAFEBAEAADCCDDCDFFFFCACEDCFCFECCACCAFEACBCCCCBEBBFFEAFCDAEFEEBBACBEECBDCFECCBBABCDDBADDAACABABCFFCBAFBBEEEAFCECCBEEFEEDCAEFFECFDFAAABCAFFEDAACFCDDABCFBAAFDDFFDEBCCFFCFFCACCFACAAFFFDADCEDCCFEDBFBDFCEEABEEDCEFFDABDEDDCEEFFFFDBDCBEDCFEDBAABABECCBFBBBEFCDFBDCACECAACDBAAADBAAACAACEBDDEBECBACBECCEFBBABABFEADAEAFBCAAFDBCABAFAEDBFCCFECBBBDDEBDABFDFAAEBDEBADFFEBFEACECEDABCDDDEAAFEEACFEFFAAAEDBBAFFBFDCFEAEECDABFDEBFECFDDCCBBBDFBEEBACAACBEDEEEADAEFFDBFBBFDFBDCCFCAAAEEDBFAEFFEBEAAEDCDABECCDAADBABBDCBBDEAADEFEFCCBBCCEFDADDCBAFBAECBEDDAAEBDFAFCBDFDBEEFCADBCDBFCCBECDEAFEEBAAAABAEFFFBABCFCFCAEBFFEAEFCBEEEFDFDEDEDBBAFFFAAABBEAECCCAEBADACFAFDBDAEDABEAECCFCACDDDFFEEEBEBBDCEFACEDBDDFCEAADFDEABEBDEBCBDDCDEAFECAAACBEACCACDFFECCCBBDCAFDACFCEBDEADADFABBCEDBEBEAEDFBDADEADFCBCFBBDDDDFCCABFEEAFEDBBFAACDDBFFDEBFCDADECFBADBCCBCAADDCEDEBFEBAFCBEDECCCFFCFDBBCCEBAAFDECAACCDFEFCCDCEBDFBABACCFCBCAEDEBCDBABFBEEBEBFFFBCBDAEAEEBBCDADCDBEBBCCAFADEEFCEEDFACABDDCBBDFDEDAECAAEFDFFEBABCDEFFFCCCCADCCDDBFEEEDACEFEBEEDEAAFDBACFBECEFEDFEFCEBBAFFDBCDACBECAAFAADCFADAABDAFABFAFFAEBACCAFFDAECFAABDDFACFDADDBADAAEFDCECEBDABAECBDBECECACBADBCBEEEDACBBDFCBCFCDDDDCAADBBAFDAFDBFBBBAEBCDCFCBDCDCEFBFDCFECDCFEEFADAACBBCBACDCFFEFEBAEEDCEABAAAFEEBDBECECDECFBCBEFEBCFDCFABAAFCDAEBBDFFFBEBFDEFFAFBEACBABFDDEFFFBFFDDEBEFDEBACEADBACFFCAADFDFDADEDCEBECDCAEECEEDDCCEFDCAFDFCBFABFAAFBAABCACDDCAEBFDAABABDDDFFFAAEECDABBCDBABBBCCEFBCACFEEBCFAAEEFBEBEEEDFEDBEDDEBEECAFFEBFCFFEDBAECADCCBBAAFAFFDDFCFBCABEAFFFEEDFBCBCFBDDCBEFDFEADEBADBCEFDDDEDCDCADEFFEDCAAFAAADAFBDDAEBAABACBCFEFEECCAABFFCAFBBBEBFCBEECECBDFFFDCACACBECAFBDEFBEEAADCBBFDFAEBDEBAFFCEDECAFCECCAFDEAECAFBFFAFBCFBEBEBADEBCFDDDECDADEBDBBDBBAAAFFFBDFCBACEBBBCFADADDFABDABCBAFACB";
            
            int count = 0;
            for (int i = 0; i < s.Length - 2; i++)
            {
                if ( ((s[i + 2] == 'C') || (s[i + 2] == 'D') || (s[i + 2] == 'F')) &&
                     ((s[i] == 'A') || (s[i] == 'D') || (s[i] == 'F')) &&
                     (s[i] != s[i + 2]) &&
                     ((s[i + 1] == 'C') || (s[i + 1] == 'D') || (s[i + 1] == 'F')) && 
                     (s[i + 1] != s[i + 2]) 
                   )
                    count++;
            }

            Console.WriteLine(count);
        }

        internal static void Solution_75()
        {
            string s = "CHHCHDCCCCHHHCCCCHCCCCCCCCCCCCC";

            int max = 0, k = 1;
            for (int i = 1; i < s.Length; i++)
                if (s[i] == s[i - 1])
                {
                    k += 1;
                    max = Math.Max(k, max);
                }
                else
                    k = 1;

            for (int i = 1; i < s.Length; i++)
                if (s[i] == s[i - 1])
                {
                    k += 1;
                    if (k == max)
                        Console.WriteLine($"{s[i]} {k}");
                }
                else
                    k = 1;
        }

        internal static void Solution_87()
        {
            string s = "CHH123CHDCCCCH235HHCCCCHCCCCC5235235CCCCC2222222CCC";

            Console.WriteLine(s.Split(s
                                      .Distinct()
                                          .Where(x => !Int32.TryParse(x.ToString(), out int y))
                                              .ToArray(), StringSplitOptions.RemoveEmptyEntries)
                                                  .Max());
        }
    }
}
